language: python

python:
    - "3.8"

compiler:
    - gcc

env:
    - TESTING_TAG=_mpich   WITHMPI=mpich
    - TESTING_TAG=_openmpi WITHMPI=openmpi
    - TESTING_TAG=_serial  WITHMPI=no
  
install:
    - if [[ "$WITHMPI" == "openmpi" ]]; then
          sudo apt-get install -qq openmpi-bin libopenmpi-dev python-mpi4py;
          update-alternatives --list mpi|grep "$WITHMPI" | xargs -rt sudo update-alternatives --set mpi;
          update-alternatives --list mpirun|grep "$WITHMPI" | xargs -rt sudo update-alternatives --set mpirun;
      fi
    - if [[ "$WITHMPI" == "mpich" ]]; then
          sudo apt-get install -qq mpich libmpich-dev python-mpi4py;
          update-alternatives --list mpi|grep "$WITHMPI" | xargs -rt sudo update-alternatives --set mpi;
          update-alternatives --list mpirun|grep "$WITHMPI" | xargs -rt sudo update-alternatives --set mpirun;
      fi

    - pip3 install numpy
    - pip3 install scipy
    - pip3 install matplotlib
    - pip3 install setuptools
    - pip3 install enum34
    - pip3 install xarray
    - pip3 install netcdf4
    - pip3 install psutil
    - pip3 install tqdm
    - pip3 install Sphinx
    - pip3 install sphinx_rtd_theme
    - pip3 install ecmwf_api_client
    - pip3 install cdsapi
    - pip3 install h5py
    - pip3 install coveralls
    - pip3 install coverage
    - pip3 install future
    - pip3 install pytest
    
    - if [[ "$WITHMPI" != "no" ]]; then
        - pip3 install mpi4py
        - pip3 install pytest-mpi
      fi


script:
    - mpirun -np 6 python3 -m pytest --with-mpi -v

after_success:
    - coveralls

branches:
    only:
        - main
